# Generated by Django 5.2.1 on 2025-05-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thulasi', '0002_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='mobile_no',
            field=models.CharField(max_length=15),
        ),
    ]
