# Generated by Django 5.2.1 on 2025-05-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('mood', models.CharField(max_length=50)),
                ('mood_intensity', models.IntegerField()),
                ('performance', models.CharField(max_length=50)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('stress_level', models.CharField(max_length=50)),
                ('energy_level', models.CharField(max_length=50)),
                ('physical_health', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('social_interaction', models.TextField(blank=True, null=True)),
                ('weather', models.CharField(blank=True, max_length=50, null=True)),
                ('mental_clarity', models.CharField(blank=True, max_length=50, null=True)),
                ('gratitude_notes', models.TextField(blank=True, null=True)),
                ('self_care', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
